namespace HermesProxy.World.Enums.V1_14_0_40237;

public enum ItemField
{
	ITEM_FIELD_OWNER = 7,
	ITEM_FIELD_CONTAINED = 11,
	ITEM_FIELD_CREATOR = 15,
	ITEM_FIELD_GIFTCREATOR = 19,
	ITEM_FIELD_STACK_COUNT = 23,
	ITEM_FIELD_DURATION = 24,
	ITEM_FIELD_SPELL_CHARGES = 25,
	ITEM_FIELD_FLAGS = 30,
	ITEM_FIELD_ENCHANTMENT = 31,
	ITEM_FIELD_PROPERTY_SEED = 70,
	ITEM_FIELD_RANDOM_PROPERTIES_ID = 71,
	ITEM_FIELD_DURABILITY = 72,
	ITEM_FIELD_MAXDURABILITY = 73,
	ITEM_FIELD_CREATE_PLAYED_TIME = 74,
	ITEM_FIELD_MODIFIERS_MASK = 75,
	ITEM_FIELD_CONTEXT = 76,
	ITEM_FIELD_ARTIFACT_XP = 77,
	ITEM_FIELD_APPEARANCE_MOD_ID = 79,
	ITEM_END = 80
}
