namespace HermesProxy.World.Enums.V2_5_2_39570;

public enum PlayerField
{
	PLAYER_DUEL_ARBITER = 215,
	PLAYER_WOW_ACCOUNT = 219,
	PLAYER_LOOT_TARGET_GUID = 223,
	PLAYER_FLAGS = 227,
	PLAYER_FLAGS_EX = 228,
	PLAYER_GUILDRANK = 229,
	PLAYER_GUILDDELETE_DATE = 230,
	PLAYER_GUILDLEVEL = 231,
	PLAYER_BYTES = 232,
	PLAYER_BYTES_2 = 233,
	PLAYER_DUEL_TEAM = 234,
	PLAYER_GUILD_TIMESTAMP = 235,
	PLAYER_QUEST_LOG = 236,
	PLAYER_VISIBLE_ITEM = 636,
	PLAYER_CHOSEN_TITLE = 674,
	PLAYER_FAKE_INEBRIATION = 675,
	PLAYER_FIELD_VIRTUAL_PLAYER_REALM = 676,
	PLAYER_FIELD_CURRENT_SPEC_ID = 677,
	PLAYER_FIELD_TAXI_MOUNT_ANIM_KIT_ID = 678,
	PLAYER_FIELD_AVG_ITEM_LEVEL = 679,
	PLAYER_FIELD_CURRENT_BATTLE_PET_BREED_QUALITY = 685,
	PLAYER_FIELD_HONOR_LEVEL = 686,
	PLAYER_FIELD_CUSTOMIZATION_CHOICES = 687,
	PLAYER_END = 759
}
