namespace HermesProxy.World.Enums.V1_14_0_40237;

public enum GameObjectField
{
	GAMEOBJECT_FIELD_CREATED_BY = 7,
	GAMEOBJECT_FIELD_GUILD_GUID = 11,
	GAMEOBJECT_DISPLAYID = 15,
	GAMEOBJECT_FLAGS = 16,
	GAMEOBJECT_PARENTROTATION = 17,
	GAMEOBJECT_FACTION = 21,
	GAMEOBJECT_LEVEL = 22,
	GAMEOBJECT_BYTES_1 = 23,
	GAMEOBJECT_SPELL_VISUAL_ID = 24,
	GAMEOBJECT_STATE_SPELL_VISUAL_ID = 25,
	GAMEOBJECT_STATE_ANIM_ID = 26,
	GAMEOBJECT_STATE_ANIM_KIT_ID = 27,
	GAMEOBJECT_STATE_WORLD_EFFECT_ID = 28,
	GAMEOBJECT_FIELD_CUSTOM_PARAM = 32,
	GAMEOBJECT_END = 33
}
