<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HermesProxy</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp6.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="HermesProxy.BNetServer.pfx" />
    <EmbeddedResource Include="HermesProxy.BNetServer.pfx" LogicalName="HermesProxy.BNetServer.pfx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Framework">
      <HintPath>Framework.dll</HintPath>
    </Reference>
    <Reference Include="Google.Protobuf">
      <HintPath>Google.Protobuf.dll</HintPath>
    </Reference>
    <Reference Include="System.Configuration.ConfigurationManager">
      <HintPath>System.Configuration.ConfigurationManager.dll</HintPath>
    </Reference>
    <Reference Include="DotNetZip">
      <HintPath>DotNetZip.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>