namespace HermesProxy.World.Enums.V3_3_5_12340;

public enum CorpseField
{
	CORPSE_FIELD_OWNER = 6,
	CORPSE_FIELD_PARTY = 8,
	CORPSE_FIELD_DISPLAY_ID = 10,
	CORPSE_FIELD_ITEM = 11,
	CORPSE_FIELD_BYTES_1 = 30,
	CORPSE_FIELD_BYTES_2 = 31,
	CORPSE_FIELD_GUILD = 32,
	CORPSE_FIELD_FLAGS = 33,
	CORPSE_FIELD_DYNAMIC_FLAGS = 34,
	CORPSE_FIELD_PAD = 35,
	CORPSE_END = 36
}
