namespace HermesProxy.World.Enums.V3_3_5_12340;

public enum DynamicObjectField
{
	DYNAMICOBJECT_CASTER = 6,
	DYNAMICOBJECT_BYTES = 8,
	DYNAMICOBJECT_SPELLID = 9,
	DYNAMICOBJECT_RADIUS = 10,
	DYNAMICOBJECT_CASTTIME = 11,
	DYNAMICOBJECT_END = 12
}
