namespace HermesProxy.World.Enums.V3_3_5_12340;

public enum GameObjectField
{
	GAMEOBJECT_FIELD_CREATED_BY = 6,
	GAMEOBJECT_DISPLAYID = 8,
	GAMEOBJECT_FLAGS = 9,
	GAMEOBJECT_PARENTROTATION = 10,
	GAMEOBJECT_DYNAMIC = 14,
	GAMEOBJECT_FACTION = 15,
	GAMEOBJECT_LEVEL = 16,
	GAMEOBJECT_BYTES_1 = 17,
	GAMEOBJECT_END = 18
}
