namespace HermesProxy.World.Enums.V1_14_1_40688;

public enum UnitDynamicField
{
	UNIT_DYNAMIC_FIELD_PASSIVE_SPELLS,
	UNIT_DYNAMIC_FIELD_WORLD_EFFECTS,
	UNIT_DYNAMIC_FIELD_CHANNEL_OBJECTS,
	UNIT_DYNAMIC_END
}
