namespace HermesProxy.World.Enums.V2_5_3_41750;

public enum PlayerField
{
	PLAYER_DUEL_ARBITER = 218,
	PLAYER_WOW_ACCOUNT = 222,
	PLAYER_LOOT_TARGET_GUID = 226,
	PLAYER_FLAGS = 230,
	PLAYER_FLAGS_EX = 231,
	PLAYER_GUILDRANK = 232,
	PLAYER_GUILDDELETE_DATE = 233,
	PLAYER_GUILDLEVEL = 234,
	PLAYER_BYTES = 235,
	PLAYER_BYTES_2 = 236,
	PLAYER_DUEL_TEAM = 237,
	PLAYER_GUILD_TIMESTAMP = 238,
	PLAYER_QUEST_LOG = 239,
	PLAYER_VISIBLE_ITEM = 639,
	PLAYER_CHOSEN_TITLE = 677,
	PLAYER_FAKE_INEBRIATION = 678,
	PLAYER_FIELD_VIRTUAL_PLAYER_REALM = 679,
	PLAYER_FIELD_CURRENT_SPEC_ID = 680,
	PLAYER_FIELD_TAXI_MOUNT_ANIM_KIT_ID = 681,
	PLAYER_FIELD_AVG_ITEM_LEVEL = 682,
	PLAYER_FIELD_CURRENT_BATTLE_PET_BREED_QUALITY = 688,
	PLAYER_FIELD_HONOR_LEVEL = 689,
	PLAYER_FIELD_CUSTOMIZATION_CHOICES = 690,
	PLAYER_END = 760
}
