namespace HermesProxy.World.Enums.V2_4_3_8606;

public enum CorpseField
{
	CORPSE_FIELD_OWNER = 6,
	CORPSE_FIELD_PARTY = 8,
	CORPSE_FIELD_FACING = 10,
	CORPSE_FIELD_POS_X = 11,
	CORPSE_FIELD_POS_Y = 12,
	CORPSE_FIELD_POS_Z = 13,
	CORPSE_FIELD_DISPLAY_ID = 14,
	CORPSE_FIELD_ITEM = 15,
	CORPSE_FIELD_BYTES_1 = 34,
	CORPSE_FIELD_BYTES_2 = 35,
	CORPSE_FIELD_GUILD = 36,
	CORPSE_FIELD_FLAGS = 37,
	CORPSE_FIELD_DYNAMIC_FLAGS = 38,
	CORPSE_FIELD_PAD = 39,
	CORPSE_END = 40
}
