namespace HermesProxy.World.Enums.V2_5_2_39570;

public enum ItemDynamicField
{
	ITEM_DYNAMIC_FIELD_MODIFIERS,
	ITEM_DYNAMIC_FIELD_BONUSLIST_IDS,
	ITEM_DYNAMIC_FIELD_ARTIFACT_POWERS,
	ITEM_DYNAMIC_FIELD_GEMS,
	ITEM_DYNAMIC_END
}
