namespace HermesProxy.Auth;

public enum AuthCommand : byte
{
	LOGON_CHALLENGE = 0,
	LOGON_PROOF = 1,
	RECONNECT_CHALLENGE = 2,
	RECONNECT_PROOF = 3,
	REALM_LIST = 16,
	TRANSFER_INITIATE = 48,
	TRANSFER_DATA = 49,
	TRANSFER_ACCEPT = 50,
	TRANSFER_RESUME = 51,
	TRANSFER_CANCEL = 52
}
