namespace HermesProxy.World.Enums.V2_5_3_41750;

public enum ActivePlayerDynamicField
{
	ACTIVE_PLAYER_DYNAMIC_FIELD_RESERACH_SITE = 4,
	ACTIVE_PLAYER_DYNAMIC_FIELD_RESEARCH_SITE_PROGRESS = 5,
	ACTIVE_PLAYER_DYNAMIC_FIELD_DAILY_QUESTS_COMPLETED = 6,
	ACTIVE_PLAYER_DYNAMIC_FIELD_AVAILABLE_QUEST_LINE_X_QUEST_ID = 7,
	ACTIVE_PLAYER_DYNAMIC_FIELD_HEIRLOOMS = 9,
	ACTIVE_PLAYER_DYNAMIC_FIELD_HEIRLOOM_FLAGS = 10,
	ACTIVE_PLAYER_DYNAMIC_FIELD_TOYS = 11,
	ACTIVE_PLAYER_DYNAMIC_FIELD_TRANSMOG = 12,
	ACTIVE_PLAYER_DYNAMIC_FIELD_CONDITIONAL_TRANSMOG = 13,
	ACTIVE_PLAYER_DYNAMIC_FIELD_SELF_RES_SPELLS = 14,
	ACTIVE_PLAYER_DYNAMIC_FIELD_CHARACTER_RESTRICTIONS = 15,
	ACTIVE_PLAYER_DYNAMIC_FIELD_SPELL_PCT_MOD_BY_LABEL = 16,
	ACTIVE_PLAYER_DYNAMIC_FIELD_SPELL_FLAT_MOD_BY_LABEL = 17,
	ACTIVE_PLAYER_DYNAMIC_FIELD_RESERACH = 18,
	ACTIVE_PLAYER_DYNAMIC_END = 19
}
