namespace HermesProxy.World.Enums.V1_12_1_5875;

public enum CorpseField
{
	CORPSE_FIELD_OWNER = 6,
	CORPSE_FIELD_FACING = 8,
	CORPSE_FIELD_POS_X = 9,
	CORPSE_FIELD_POS_Y = 10,
	CORPSE_FIELD_POS_Z = 11,
	CORPSE_FIELD_DISPLAY_ID = 12,
	CORPSE_FIELD_ITEM = 13,
	CORPSE_FIELD_BYTES_1 = 32,
	CORPSE_FIELD_BYTES_2 = 33,
	CORPSE_FIELD_GUILD = 34,
	CORPSE_FIELD_FLAGS = 35,
	CORPSE_FIELD_DYNAMIC_FLAGS = 36,
	CORPSE_FIELD_PAD = 37,
	CORPSE_END = 38
}
