namespace HermesProxy.World.Enums.V1_12_1_5875;

public enum DynamicObjectField
{
	DYNAMICOBJECT_CASTER = 6,
	DYNAMICOBJECT_BYTES = 8,
	DYNAMICOBJECT_SPELLID = 9,
	DYNAMICOBJECT_RADIUS = 10,
	DYNAMICOBJECT_POS_X = 11,
	DYNAMICOBJECT_POS_Y = 12,
	DYNAMICOBJECT_POS_Z = 13,
	DYNAMICOBJECT_FACING = 14,
	DYNAMICOBJECT_PAD = 15,
	DYNAMICOBJECT_END = 16
}
