namespace HermesProxy.World.Enums.V1_12_1_5875;

public enum GameObjectField
{
	GAMEOBJECT_FIELD_CREATED_BY = 6,
	GAMEOBJECT_DISPLAYID = 8,
	GAMEOBJECT_FLAGS = 9,
	GAMEOBJECT_ROTATION = 10,
	GAMEOBJECT_STATE = 14,
	GAMEOBJECT_POS_X = 15,
	GAMEOBJECT_POS_Y = 16,
	GAMEOBJECT_POS_Z = 17,
	GAMEOBJECT_FACING = 18,
	GAMEOBJECT_DYN_FLAGS = 19,
	GAMEOBJECT_FACTION = 20,
	GAMEOBJECT_TYPE_ID = 21,
	GAMEOBJECT_LEVEL = 22,
	GAMEOBJECT_ARTKIT = 23,
	GAMEOBJECT_ANIMPROGRESS = 24,
	GAMEOBJECT_PADDING = 25,
	GAMEOBJECT_END = 26
}
