namespace HermesProxy.World.Enums.V1_12_1_5875;

public enum ItemField
{
	ITEM_FIELD_OWNER = 6,
	ITEM_FIELD_CONTAINED = 8,
	ITEM_FIELD_CREATOR = 10,
	ITEM_FIELD_GIFTCREATOR = 12,
	ITEM_FIELD_STACK_COUNT = 14,
	ITEM_FIELD_DURATION = 15,
	ITEM_FIELD_SPELL_CHARGES = 16,
	ITEM_FIELD_FLAGS = 21,
	ITEM_FIELD_ENCHANTMENT = 22,
	ITEM_FIELD_PROPERTY_SEED = 43,
	ITEM_FIELD_RANDOM_PROPERTIES_ID = 44,
	ITEM_FIELD_ITEM_TEXT_ID = 45,
	ITEM_FIELD_DURABILITY = 46,
	ITEM_FIELD_MAXDURABILITY = 47,
	ITEM_END = 48
}
