namespace HermesProxy.World.Enums.V1_14_1_40688;

public enum AreaTriggerField
{
	AREATRIGGER_OVERRIDE_SCALE_CURVE = 7,
	AREATRIGGER_EXTRA_SCALE_CURVE = 14,
	AREATRIGGER_CASTER = 21,
	AREATRIGGER_DURATION = 25,
	AREATRIGGER_TIME_TO_TARGET = 26,
	AREATRIGGER_TIME_TO_TARGET_SCALE = 27,
	AREATRIGGER_TIME_TO_TARGET_EXTRA_SCALE = 28,
	AREATRIGGER_SPELLID = 29,
	AREATRIGGER_SPELL_FOR_VISUALS = 30,
	AREATRIGGER_SPELL_X_SPELL_VISUAL_ID = 31,
	AREATRIGGER_BOUNDS_RADIUS_2D = 32,
	AREATRIGGER_DECAL_PROPERTIES_ID = 33,
	AREATRIGGER_CREATING_EFFECT_GUID = 34,
	AREATRIGGER_END = 38
}
