namespace HermesProxy.World.Enums.V1_14_1_40688;

public enum DynamicObjectField
{
	DYNAMICOBJECT_CASTER = 7,
	DYNAMICOBJECT_TYPE = 11,
	DYNAMICOBJECT_SPELL_X_SPELL_VISUAL_ID = 12,
	DYNAMICOBJECT_SPELLID = 13,
	DYNAMICOBJECT_RADIUS = 14,
	DYNAMICOBJECT_CASTTIME = 15,
	DYNAMICOBJECT_END = 16
}
