namespace HermesProxy.World.Enums;

public enum AreaTriggerField
{
	AREATRIGGER_OVERRIDE_SCALE_CURVE,
	AREATRIGGER_EXTRA_SCALE_CURVE,
	AREATRIGGER_CASTER,
	AREATRIGGER_DURATION,
	AREATRIGGER_TIME_TO_TARGET,
	AREATRIGGER_TIME_TO_TARGET_SCALE,
	AREATRIGGER_TIME_TO_TARGET_EXTRA_SCALE,
	AREATRIGGER_SPELLID,
	AREATRIGGER_SPELL_FOR_VISUALS,
	AREATRIGGER_SPELL_X_SPELL_VISUAL_ID,
	AREATRIGGER_BOUNDS_RADIUS_2D,
	AREATRIGGER_DECAL_PROPERTIES_ID,
	AREATRIGGER_CREATING_EFFECT_GUID,
	AREATRIGGER_END
}
