namespace HermesProxy.World.Enums;

public enum AuthResult : byte
{
	AUTH_OK = 12,
	AUTH_FAILED,
	AUTH_REJECT,
	AUTH_BAD_SERVER_PROOF,
	AUTH_UNAVAILABLE,
	AUTH_SYSTEM_ERROR,
	AUTH_BILLING_ERROR,
	AUTH_BILLING_EXPIRED,
	AUTH_VERSION_MISMATCH,
	AUTH_UNKNOWN_ACCOUNT,
	AUTH_INCORRECT_PASSWORD,
	AUTH_SESSION_EXPIRED,
	AUTH_SERVER_SHUTTING_DOWN,
	AUTH_ALREADY_LOGGING_IN,
	AUTH_LOGIN_SERVER_NOT_FOUND,
	AUTH_WAIT_QUEUE,
	AUTH_BANNED,
	AUTH_ALREADY_ONLINE,
	AUTH_NO_TIME,
	AUTH_DB_BUSY,
	AUTH_SUSPENDED,
	AUTH_PARENTAL_CONTROL,
	AUTH_LOCKED_ENFORCED
}
