namespace HermesProxy.World.Enums;

public enum AzeriteItemField
{
	AZERITE_ITEM_FIELD_XP,
	AZERITE_ITEM_FIELD_LEVEL,
	AZERITE_ITEM_FIELD_AURA_LEVEL,
	AZERITE_ITEM_FIELD_KNOWLEDGE_LEVEL,
	AZERITE_ITEM_FIELD_DEBUG_KNOWLEDGE_WEEK,
	AZERITE_ITEM_END
}
