namespace HermesProxy.World.Enums;

public enum ChatMessageTypeWotLK : uint
{
	System = 0u,
	Say = 1u,
	Party = 2u,
	Raid = 3u,
	Guild = 4u,
	Officer = 5u,
	Yell = 6u,
	Whisper = 7u,
	WhisperForeign = 8u,
	WhisperInform = 9u,
	Emote = 10u,
	TextEmote = 11u,
	MonsterSay = 12u,
	MonsterParty = 13u,
	MonsterYell = 14u,
	MonsterWhisper = 15u,
	MonsterEmote = 16u,
	Channel = 17u,
	ChannelJoin = 18u,
	ChannelLeave = 19u,
	ChannelList = 20u,
	ChannelNotice = 21u,
	ChannelNoticeUser = 22u,
	Afk = 23u,
	Dnd = 24u,
	Ignored = 25u,
	Skill = 26u,
	Loot = 27u,
	Money = 28u,
	Opening = 29u,
	Tradeskills = 30u,
	PetInfo = 31u,
	CombatMiscInfo = 32u,
	CombatXPGain = 33u,
	CombatHonorGain = 34u,
	CombatFactionChange = 35u,
	BattlegroundNeutral = 36u,
	BattlegroundAlliance = 37u,
	BattlegroundHorde = 38u,
	RaidLeader = 39u,
	RaidWarning = 40u,
	RaidBossEmote = 41u,
	RaidBossWhisper = 42u,
	Filtered = 43u,
	Battleground = 44u,
	BattlegroundLeader = 45u,
	Restricted = 46u,
	BattleNet = 47u,
	Achievement = 48u,
	GuildAchievement = 49u,
	ArenaPoints = 50u,
	PartyLeader = 51u,
	Addon = uint.MaxValue
}
