namespace HermesProxy.World.Enums;

public enum ChatMessageTypeVanilla : uint
{
	System = 10u,
	Say = 0u,
	Party = 1u,
	Raid = 2u,
	Guild = 3u,
	Officer = 4u,
	Yell = 5u,
	Whisper = 6u,
	WhisperInform = 7u,
	Emote = 8u,
	TextEmote = 9u,
	MonsterSay = 11u,
	MonsterYell = 12u,
	MonsterEmote = 13u,
	Channel = 14u,
	ChannelJoin = 15u,
	ChannelLeave = 16u,
	ChannelList = 17u,
	ChannelNotice = 18u,
	ChannelNoticeUser = 19u,
	Afk = 20u,
	Dnd = 21u,
	Ignored = 22u,
	Skill = 23u,
	Loot = 24u,
	CombatMiscInfo = 25u,
	MonsterWhisper = 26u,
	MonsterParty = 48u,
	BattlegroundNeutral = 82u,
	BattlegroundAlliance = 83u,
	BattlegroundHorde = 84u,
	RaidLeader = 87u,
	RaidWarning = 88u,
	RaidBossEmote = 90u,
	RaidBossWhisper = 91u,
	Battleground = 92u,
	BattlegroundLeader = 93u,
	Addon = uint.MaxValue
}
