namespace HermesProxy.World.Enums;

public enum CorpseField
{
	CORPSE_END,
	[UpdateField(UpdateFieldType.Bytes)]
	CORPSE_FIELD_BYTES_1,
	[UpdateField(UpdateFieldType.Bytes)]
	CORPSE_FIELD_BYTES_2,
	CORPSE_FIELD_CUSTOM_DISPLAY_OPTION,
	CORPSE_FIELD_DISPLAY_ID,
	CORPSE_FIELD_DYNAMIC_FLAGS,
	CORPSE_FIELD_FACTIONTEMPLATE,
	CORPSE_FIELD_FLAGS,
	CORPSE_FIELD_GUILD,
	CORPSE_FIELD_GUILD_GUID,
	CORPSE_FIELD_ITEM,
	[UpdateField(UpdateFieldType.Guid)]
	CORPSE_FIELD_OWNER,
	CORPSE_FIELD_PAD,
	CORPSE_FIELD_PARTY
}
