namespace HermesProxy.World.Enums;

public enum PlayerDynamicField
{
	PLAYER_DYNAMIC_END,
	PLAYER_DYNAMIC_FIELD_ARENA_COOLDOWNS,
	PLAYER_DYNAMIC_FIELD_AVAILABLE_QUEST_LINE_X_QUEST_ID,
	PLAYER_DYNAMIC_FIELD_CHARACTER_RESTRICTIONS,
	PLAYER_DYNAMIC_FIELD_CONDITIONAL_TRANSMOG,
	PLAYER_DYNAMIC_FIELD_DAILY_QUESTS,
	PLAYER_DYNAMIC_FIELD_HEIRLOOM_FLAGS,
	PLAYER_DYNAMIC_FIELD_HEIRLOOMS,
	PLAYER_DYNAMIC_FIELD_RESEARCH_SITE_PROGRESS,
	PLAYER_DYNAMIC_FIELD_RESERACH_SITE,
	PLAYER_DYNAMIC_FIELD_SELF_RES_SPELLS,
	PLAYER_DYNAMIC_FIELD_SPELL_FLAT_MOD_BY_LABEL,
	PLAYER_DYNAMIC_FIELD_SPELL_PCT_MOD_BY_LABEL,
	PLAYER_DYNAMIC_FIELD_TOYS,
	PLAYER_DYNAMIC_FIELD_TRANSMOG
}
