namespace HermesProxy.World.Enums;

public enum SceneObjectField
{
	SCENEOBJECT_FIELD_CREATEDBY,
	SCENEOBJECT_FIELD_END,
	SCENEOBJECT_FIELD_RND_SEED_VAL,
	SCENEOBJECT_FIELD_SCENE_TYPE,
	SCENEOBJECT_FIELD_SCRIPT_PACKAGE_ID
}
