namespace HermesProxy.World.Enums;

public enum UnitDynamicField
{
	UNIT_DYNAMIC_FIELD_CHANNEL_OBJECTS,
	UNIT_DYNAMIC_FIELD_PASSIVE_SPELLS,
	UNIT_DYNAMIC_FIELD_WORLD_EFFECTS,
	UNIT_DYNAMIC_END
}
